### ISSUE TITLE
Error when building project for the first time: Error: ENOENT

### ISSUE THREAD

**Issue by williamrjribeiro** [WebReflection/require_client#1]
Hello,

when I try to compile it for production with:
`sudo require_client myproject/js release/myproject.js`

I get:
`[require_client] build #1`

`fs.js:230`
`  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);`
                 ^
`Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/require_client/build/require_parsed.js'
    at Object.openSync (fs.js:230:18)
    at Object.writeFileSync (fs.js:618:15)
    at /usr/local/lib/node_modules/require_client/require_client:137:10
    at Timer.next (/usr/local/lib/node_modules/require_client/require_client:8:35)`

This issue happens with **Node version: v0.6.5 and v0.8.12, npm v1.1.63 on Mac OSX (10.7.7).**

The workaround is to manually create the folder **/usr/local/lib/node_modules/require_client/build**.

**Comment by WebReflection** [comment]
closing and flagging this module as deprecated
